[package]
edition = "2018"
name = "backend"
version = "0.1.0"

[dependencies]
actix-web = "3"
chrono = "0.4"
futures = "0.3"
futures-util = "0.3"
serde = "1"
serde_json = "1"

[dependencies.tokio]
features = ["full"]
version = "1.12.0"
