[package]
edition = "2018"
name = "message-backend"
version = "0.1.0"

[dependencies]
actix-web = "3"

futures-util = "0.3"
futures = "0.3"

serde = "1"
serde_json = "1"
chrono = "0.4"
# once_cell = "1.8"

tokio = { version = "1.12.0", features = ["full"] }