[package]
edition = "2018"
name = "message-client"
version = "0.1.0"

[dependencies]
reqwest = { version = "0.11.5", features = ["stream"] }
tokio = { version = "1.12.0", features = ["full"] }
futures-util = "0.3.17"